package com.example.nexora.ai

/**
 * Represents a tool that the AI Agent can use.
 */
interface AiTool {
    val name: String
    val description: String
    val riskLevel: ToolRiskLevel
    
    suspend fun execute(parameters: Map<String, Any>): ToolResult
}

enum class ToolRiskLevel {
    SAFE,        // Read-only
    LOW_RISK,    // Create/Update
    HIGH_RISK,   // Major changes
    DESTRUCTIVE  // Delete
}

data class ToolResult(
    val success: Boolean,
    val data: Any? = null,
    val message: String,
    val error: String? = null
)

/**
 * Represents the status of the AI Agent during request processing.
 */
enum class AiAgentStatus {
    PLANNING,
    EXECUTING,
    REASONING,
    VERIFYING,
    COMPLETED,
    FAILED,
    AWAITING_CONFIRMATION
}

/**
 * A multi-step plan generated by the AI Agent.
 */
data class AiAgentPlan(
    val goal: String,
    val steps: List<AiAgentStep>,
    val status: AiAgentStatus = AiAgentStatus.PLANNING
)

/**
 * A single step in an AI Agent plan.
 */
data class AiAgentStep(
    val stepId: String,
    val toolName: String,
    val parameters: Map<String, Any>,
    val reason: String,
    val status: StepStatus = StepStatus.PENDING,
    val result: ToolResult? = null,
    val requiresConfirmation: Boolean = false
)

enum class StepStatus {
    PENDING,
    RUNNING,
    COMPLETED,
    FAILED,
    SKIPPED
}
